# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BoundingGeometries
                                 A QGIS plugin
 Mnimum bouding geometries for polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-18
        copyright            : (C) 2023 by Leo Guzman
        email                : kuma@mailfence.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BoundingGeometries class from file BoundingGeometries.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bounding_geometries import BoundingGeometries
    return BoundingGeometries(iface)
